helm-doc-first-draft
datastax/pulsar-docs pull request #30
Opened 2021-11-16 22:24 UTC by mendonk

First draft

2021-11-17 19:39 UTC, jgillenwater requested changes
I think the structure is good, but the descriptions are documented inconsistently. Some state the key name to start the description. Some use more active language in the verb. Please edit for consistency and submit for review again.

2021-11-17 19:39 UTC, jgillenwater commented on modules/ROOT/pages/helm-chart-config.adoc
> +You can override chart configurations during installation as necessary if you’re an advanced user, or make changes after a default installation using `helm upgrade` at a later time.
```suggestion
This page explains configuration values included in the Helm chart https://github.com/datastax/pulsar-helm-chart/blob/master/helm-chart-sources/pulsar/values.yaml[values file].

If you are an advanced user, you can override chart configurations during installation as necessary or make changes after a default installation using `helm upgrade` at a later time.
```

2021-11-17 19:39 UTC, jgillenwater commented on modules/ROOT/pages/helm-chart-config.adoc
> +| rbac | bool | `true` | use `ClusterRole` and `ClusterRoleBinding` resources when set to `true``, use namespace Role and RoleBinding resources when set to `false`
```suggestion
| rbac | bool | `true` | Uses `ClusterRole` and `ClusterRoleBinding` resources when set to `true`; uses `NamespaceRole` and `RoleBinding` resources when set to `false` 
```

2022-12-14 17:39 UTC, mendonk commented
This will be doc'd as part of a larger effort in this repo, so this PR is no longer useful.

2022-12-14 17:39 UTC, closed without merging