Ls 456 auth
datastax/pulsar-docs pull request #34
Opened 2022-01-04 20:56 UTC by mendonk

first draft

2022-02-10 15:33 UTC, jgillenwater requested changes
Please see comments, make changes to remaining docs, and resubmit.

2022-02-10 15:33 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +authentication in Pulsar, go https://pulsar.apache.org/docs/en/security-token-admin/[here].
```suggestion
The Helm chart can enable token-based authentication for your Pulsar cluster. For more, see https://pulsar.apache.org/docs/en/security-token-admin/[Pulsar token authentication].
```

2022-02-10 15:33 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +For authentication to work, the token-generation keys need to be stored in Kubernetes secrets along with some default tokens (for superuser access).
What does superuser apply to? Is it required for any authentication? Or are the default tokens used for superuser access?

2022-02-10 15:33 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +== Authentication
```suggestion
```

2022-02-10 15:33 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +== Authentication
Move headings up a level b/c everything is in authentication, which is this entire topic.

2022-02-10 15:33 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +=== Automatic generation of secrets for Pulsar token authentication
```suggestion
== Automatic generation of secrets for Pulsar token authentication
```

2022-02-10 15:33 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +Use the following settings to enable automatic generation of the secrets and enable token-based authentication:
Where is this updated? What is the yaml name?

2022-02-10 15:33 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +When the provision container is enabled, it will check if the required secrets exist. If they don't exist, it will generate new token keys and use those keys to generate the default set of tokens.
How do I get from enabling > secrets > tokens? What do I do with the tokens next?

2022-02-10 15:33 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +A number of values need to be stored in secrets prior to enabling token-based authentication. First, you need to generate a key-pair for signing the tokens using the Pulsar tokens command:
```suggestion
A number of values need to be stored in secrets prior to enabling token-based authentication.

. Generate a key-pair for signing the tokens using the Pulsar tokens command:
```

2022-02-10 15:33 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +
```suggestion
+
----
bin/pulsar tokens create-key-pair --output-private-key my-private.key --output-public-key my-public.key
----
+
[TIP]
====
The names of the files used in this section match the default values in the chart. If you used different names, then you will have to update the corresponding values.
====

. Store those keys as secrets.
+
```

2022-02-10 15:33 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +
```suggestion
+
----
kubectl create secret generic token-public-key \
 --from-file=my-public.key \
 --namespace pulsar
----

. Using those keys, generate tokens for the following subjects (roles): 
+
* `admin`
* `superuser`
* `proxy`
* `websocket` (only required if using the standalone WebSocket proxy)
+
----
bin/pulsar tokens create --private-key file:///pulsar/token-private-key/my-private.key --subject <subject>
----

. Add each token as a secret:
+
----
kubectl create secret generic token-<subject> \
 --from-file=<subject>.jwt \
 --namespace pulsar
----

. Enable token-based authentication with this setting in `devvalues.yaml:
+
----
enableTokenAuth: yes
----

```

2022-02-15 15:24 UTC, michaeljmarshall commented on modules/ROOT/pages/auth.adoc
> +DataStax created the https://github.com/datastax/pulsar-openid-connect-plugin[Pulsar OpenID Connect Authentication Plugin] to provide a more dynamic authentication option for Pulsar. This plugin inte
Nit: the plugin is supposed to integrate with any OpenID Connect compliant Identity Provider. We use Keycloak as an example, but the spec should allow us to integrate with Okta, Azure AD, and other providers. We haven't not yet tested with these providers, so there is a chance that small adjustments will need to be made.

2022-05-27 14:53 UTC, jgillenwater approved these changes
Minor suggestion

2022-05-27 14:53 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +
Consider making this a partial and add into `quickstart-helm-installs.adoc`.

2022-05-27 14:53 UTC, jgillenwater commented on modules/ROOT/pages/auth.adoc
> +== Next
```suggestion
== What's next?
```

2022-05-27 17:57 UTC, merged