io-connectors
datastax/pulsar-docs pull request #41
Opened 2022-01-11 16:52 UTC by mendonk

2022-01-18 14:30 UTC, nicoloboschi requested changes

2022-01-18 14:30 UTC, nicoloboschi commented on modules/ROOT/pages/io-connectors.adoc
> +When you have Luna Streaming installed and running, add IO connectors to your deployment to interact with external systems, such as Apache Cassandra, Aerospike, and many others.
Aerospike is not included in Luna Streaming. See https://github.com/datastax/release-notes/blob/master/Luna_Streaming_2.8_Release_Notes.md#builtin-connectors

2022-01-18 14:30 UTC, nicoloboschi commented on modules/ROOT/pages/io-connectors.adoc
> +Explore source connector configurations and code examples https://pulsar.apache.org/docs/en/io-connectors/#source-connector[here].
broken link ?

2022-01-18 14:30 UTC, nicoloboschi commented on modules/ROOT/pages/io-connectors.adoc
> +Sink connectors are used to pull messages _from_ Pulsar topics and persist the messages _to_ external topics.
```suggestion
Sink connectors are used to pull messages _from_ Pulsar topics and persist the messages _to_ external systems.
```

2022-01-18 14:30 UTC, nicoloboschi commented on modules/ROOT/pages/io-connectors.adoc
> +== Processing Guarantees
Why don't we just point out to the Pulsar official docs ?

2022-02-17 23:33 UTC, jgillenwater requested changes

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +When you have Luna Streaming installed and running, add IO connectors to your deployment to interact with external systems, such as Apache Cassandra, Elastic Search, and many others.
```suggestion
When you have Luna Streaming installed and running, add IO connectors to your deployment to interact with external systems, such as Apache Cassandra®, Elasticsearch, and others.
```

@mendonk Make sure you use ® for first use of Apache Cassandra on each page and format Elasticsearch properly each time (no space, lowercase S).

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +Source connectors pull messages _from_ external topics and persist the messages _to_ Pulsar topics.
```suggestion
Source connectors pull messages from external topics and persist the messages to Apache Pulsar™ topics.
```

Emphasis isn't required. Include "Apache" and ™ for first reference of Pulsar on a page.

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +Sink connectors are used to pull messages _from_ Pulsar topics and persist the messages _to_ external systems.
```suggestion
Sink connectors are used to pull messages from Pulsar topics and persist the messages to external systems.
```

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> += Luna Streaming IO Connectors
```suggestion
= Luna Streaming IO connectors
```

Capitalize first word and proper nouns only. See below also.

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +== Source Connectors
```suggestion
== Source connectors
```

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +== Processing Guarantees
```suggestion
== Processing guarantees
```

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +== Kafka Connectors
```suggestion
== Kafka connectors
```

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +Datastax offers https://github.com/datastax/pulsar-3rdparty-connector[third-party connector support] for creating Pulsar connectors on the base of existing Kafka connectors. This allows developers to
```suggestion
DataStax offers https://github.com/datastax/pulsar-3rdparty-connector[third-party connector support] for creating Pulsar connectors on the base of existing Kafka connectors. This allows developers to quickly move connectors from their Apache Kafka® infrastructure into Pulsar.
```

DataStax has a capital D and S. Use ® for first use of Kafka on page.

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +**Prerequisites:**
```suggestion
== Prerequisites
```

Prereq title should be at same level of the procedure headings.

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +* The connector's `.nar` files can be found at `pulsar-connectors/<connector name>>/target/pulsar-3rdparty-pulsar-connectors-<connector name>-0.1.0-SNAPSHOT.nar`.
```suggestion
* JDK 11+ installed.
* Maven 3.8 installed.
* Clone the connector's repo. Run `mvn clean install` from the root.

The connector's `.nar` files can be found at `pulsar-connectors/<connector name>/target/pulsar-3rdparty-pulsar-connectors-<connector name>-0.1.0-SNAPSHOT.nar`.
```

I think the command is just `mvn clean install`. Please confirm

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +Follow the documentation https://pulsar.apache.org/docs/en/io-use/[here] to initialize your connector. Then, modify its `config.yaml` file as below to create an adapter for the connector. For further
@mendonk Let's give them enough basic steps they can do it here. Then we can point to the pulsar docs for more info.

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +=== Configuring connectors
```suggestion
== Configuring connectors
```

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +==== Sink Connectors
```suggestion
=== Sink connector `config.yaml` example
```

Is this section title more accurate?

2022-02-17 23:33 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +==== Source Connectors
```suggestion
=== Source connectors `config.yaml` example
```

2022-03-07 14:55 UTC, jgillenwater approved these changes

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +== Adding third party connectors
```suggestion
== Adding third-party connectors
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +. https://maven.apache.org/download.cgi?Preferred=ftp://ftp.osuosl.org/pub/apache/[Maven 3.8^] installed.
```suggestion
. https://www.oracle.com/java/technologies/downloads/[JDK 11+^] installed.
. https://maven.apache.org/download.cgi?Preferred=ftp://ftp.osuosl.org/pub/apache/[Maven 3.8^] installed.
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +== Building connectors
```suggestion
=== Building connectors
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +For further information on shading and troubleshooting, see the https://github.com/datastax/pulsar-3rdparty-connector[Third party connectors GitHub readme^].
```suggestion
For more information on shading and troubleshooting, see the https://github.com/datastax/pulsar-3rdparty-connector[Third-party connectors GitHub readme^].
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +
```suggestion
* *Source connectors:* Source connectors pull messages from external topics and persist the messages to Apache Pulsar™ topics. For more, see https://pulsar.apache.org/docs/en/io-connectors/#source-connector[Pulsar built-in connectors^].

* *Sink connectors:* Sink connectors pull messages from Pulsar topics and persist the messages to external systems. For more, see https://pulsar.apache.org/docs/en/io-connectors/#sink-connector[Pulsar built-in connectors^].
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +Processing guarantees are used to handle errors when writing messages to Pulsar topics.
```suggestion
Processing guarantees handle errors when writing messages to Pulsar topics:
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +. Modify the connector's `config.yaml` file to match the connector YAML files below. This creates an adapter for the connector.
```suggestion
. Clone the connector's repo. 
. Run `mvn clean install` from the root.
. Copy the connector's `.nar` file to the `connectors` directory in the Pulsar director.
+
[NOTE]
====
The connector's `.nar` files can be found at `pulsar-connectors/<connector_name>/target/pulsar-3rdparty-pulsar-connectors-<connector_name>-0.1.0-SNAPSHOT.nar`.
====

. Modify the connector's `config.yaml` file to match the connector YAML files below. 
+
This creates an adapter for the connector. 
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +[SOURCE, shell]
```suggestion
[source, shell]
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +[SOURCE, shell]
```suggestion
[source, shell]
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +. Maven dependency conflict of transitive dependencies in build time, or dependency conflict in runtime caused by third-party dependencies packaged with the connector. To resolve third-party dependen
```suggestion
These are common solutions for problems encountered while using KCA to create a new connector:

. Ensure the connector's license allows its use and redistribution. For more, see the https://www.apache.org/legal/resolved.html[Apache third-party license policy^].
. Resolve third-party dependencies if there is a Maven dependency conflict of transitive dependencies in build time or dependency conflict in runtime caused by third-party dependencies packaged with the connector. To resolve third-party dependencies, see xref:io-connectors.adoc#shading[Shading third-party connectors^].
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +If your connector includes third-party dependencies, you may need to rename some classes. This is called "shading".
```suggestion
If your connector includes third-party dependencies, you may need to rename some classes. This is called "shading."
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +. Copy `shaded-dependencies/template-shaded/` to `shaded-dependencies/<connector name>` and add the new module into `shaded-dependencies/pom.xml`.
```suggestion
. Copy `shaded-dependencies/template-shaded/` to `shaded-dependencies/<connector_name>`. 
. Add the new module into `shaded-dependencies/pom.xml`.
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +. Run `mvn dependency:tree -verbose` to review how Maven auto-resolved potential dependency conflicts. Fix as needed.
```suggestion
. Ensure third-party dependencies are renamed as specified in `shaded-dependencies/<connector name>/pom.xml` 
. Build with `mvn clean install`.
. Copy `pulsar-connectors/template/` to `pulsar-connectors/<connector_name>/`.
. Add the new module into `pulsar-connectors/pom.xml`.
. Update the `pulsar-connectors/<connector name>/README.md`.
. Build with `mvn clean install`. 
. Run `mvn dependency:tree -verbose` to review how Maven auto-resolved potential dependency conflicts. Fix as needed.
```

2022-03-07 14:55 UTC, jgillenwater commented on modules/ROOT/pages/io-connectors.adoc
> +
```suggestion
Learn more about Pulsar IO connectors https://pulsar.apache.org/docs/en/io-overview/[here^].
```

2022-03-07 21:05 UTC, merged