LS-461-first-draft
datastax/pulsar-docs pull request #42
Opened 2022-01-12 18:09 UTC by mendonk

Basics from doc. Needs more.

2022-01-13 19:52 UTC, cdbartholomew requested changes

2022-01-13 19:52 UTC, cdbartholomew commented on modules/ROOT/pages/heartbeat-vm.adoc
> +The release page is at https://github.com/datastax/pulsar-heartbeat/releases. The latest version is 1.0.12, which matches with the Git release tag and Docker image.
Can we remove the explicit version number so that we don't have to keep this updated?

2022-01-14 17:29 UTC, jgillenwater commented on modules/ROOT/pages/heartbeat-vm.adoc
> +Once the file is downloaded, uncompress the file with Gunzip. It will become a binary that can be executed. The filename structure is `pulsar-heartbeat-{version}-{os}-{arch}`.
```suggestion
. Use the Linux commands `uname -m` and `uname -o` to determine your process architecture.
+
For example, `uname -m` in Ubuntu might return `x86_64`, and `uname -o` returns `GNU/Linux`.

. Download the heartbeat binary `.gz` file matching your OS and process architecture from the https://github.com/datastax/pulsar-heartbeat/releases[releases page].

. Uncompress the file to be an executable binary. The filename structure is `pulsar-heartbeat-{version}-{os}-{arch}`. 
```

2022-01-14 17:29 UTC, jgillenwater commented on modules/ROOT/pages/heartbeat-vm.adoc
> +Here is an example:
```suggestion
Here is an example using Gunzip:
```

2022-01-14 17:29 UTC, jgillenwater commented on modules/ROOT/pages/heartbeat-vm.adoc
> +[subs=attributes+]
```suggestion
The Pulsar Heartbeat configuration is defined by a `.yaml` file. A yaml template for Heartbeat is available at https://github.com/datastax/pulsar-heartbeat/blob/master/config/runtime-template.yml[]. In this file, the environmental variable `PULSAR_OPS_MONITOR_CFG` tells the application where to source the file. 

Run the binary file `pulsar-heartbeat-{version}-{os}-{arch}`.

Here is an example of how to set up and run the application:

[subs=attributes+]
```

2022-01-14 17:29 UTC, jgillenwater commented on modules/ROOT/pages/heartbeat-vm.adoc
> +To install Heartbeat packaged with the Luna Streaming Helm chart, see xref:quickstart-helm-installs.adoc[Helm Chart Installation].
@mendonk Is this a next step or an alternative path?

2022-01-14 19:41 UTC, jgillenwater approved these changes

2022-01-14 19:42 UTC, merged