Ls 447 prod cluster
datastax/pulsar-docs pull request #55
Opened 2022-04-28 15:04 UTC by mendonk

* CDC enabled pulsar recommendations
* Helm production recs from rodrigo

2022-07-25 17:34 UTC, yabinmeng requested changes
Since production recommendation is an important topic, I think we need to be a little bit more thorough with this document. 

Also I don't think it is needed to put capacity planning as part of the production recommendation doc for general public usage. The customer oriented deployment recommendation is not suitable to be put as part of the general usage document.

If you have questions, let's set up a meeting to discuss.

2022-07-25 17:34 UTC, yabinmeng commented on modules/ROOT/pages/production-cluster.adoc
> +.Pulsar Kubernetes cluster node specifications
Again, double check this with engineering.

2022-07-25 17:34 UTC, yabinmeng commented on modules/ROOT/pages/production-cluster.adoc
> +|m6a.2xlarge
This is only relevant to AWS. You may want to state this fact.

2023-03-10 18:09 UTC, mendonk commented
Superseded by https://github.com/datastax/pulsar-docs/pull/105

2023-03-10 18:09 UTC, closed without merging